//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhutLongCompany.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NhutLongCompanyEntities : DbContext
    {
        public NhutLongCompanyEntities()
            : base("name=NhutLongCompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminMenu> AdminMenus { get; set; }
        public virtual DbSet<tbl_Config_FlowName> tbl_Config_FlowName { get; set; }
        public virtual DbSet<tbl_Config_Step> tbl_Config_Step { get; set; }
        public virtual DbSet<tbl_Config_StepInFlow> tbl_Config_StepInFlow { get; set; }
        public virtual DbSet<tbl_Customers> tbl_Customers { get; set; }
        public virtual DbSet<tbl_FlowPauseTime> tbl_FlowPauseTime { get; set; }
        public virtual DbSet<tbl_Note> tbl_Note { get; set; }
        public virtual DbSet<tbl_OrderTem> tbl_OrderTem { get; set; }
        public virtual DbSet<tbl_OrderTem_BaoGia> tbl_OrderTem_BaoGia { get; set; }
        public virtual DbSet<tbl_OrderTem_BaoGia_Detail> tbl_OrderTem_BaoGia_Detail { get; set; }
        public virtual DbSet<tbl_OrderTemPause> tbl_OrderTemPause { get; set; }
        public virtual DbSet<tbl_Products> tbl_Products { get; set; }
        public virtual DbSet<tbl_QuyTrinh> tbl_QuyTrinh { get; set; }
        public virtual DbSet<tbl_Stack> tbl_Stack { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
