//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhutLongCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Products
    {
        public int ID_Products { get; set; }
        public string NameProducts { get; set; }
        public Nullable<int> SolopProducts { get; set; }
        public string LoaigiayProducts { get; set; }
        public string OffsetFlexoProducts { get; set; }
        public string DanKimProducts { get; set; }
        public string GiaProducts { get; set; }
        public Nullable<System.DateTime> CreatedDateProducts { get; set; }
        public Nullable<System.DateTime> ModifyDateProducts { get; set; }
        public string CreateUserProducts { get; set; }
        public string ModifyUserProducts { get; set; }
        public Nullable<int> StatusProducts { get; set; }
        public string CodeProducts { get; set; }
        public string QuyCachProducts { get; set; }
        public Nullable<System.DateTime> date_deliver { get; set; }
        public string address_deliver { get; set; }
    }
}
