//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhutLongCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Config_StepInFlow
    {
        public int ID { get; set; }
        public Nullable<int> ID_Step { get; set; }
        public Nullable<int> ID_Flow { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string DienGiai { get; set; }
    }
}
