//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhutLongCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Stack
    {
        public int baoGia_detail_id { get; set; }
        public Nullable<int> index_view { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
    }
}
