//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhutLongCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customers
    {
        public int IDCustomers { get; set; }
        public string NameCustomers { get; set; }
        public string ChucvuCustomers { get; set; }
        public string CongTyCustomers { get; set; }
        public string CodeCustomers { get; set; }
        public string EmailCustomers { get; set; }
        public string PhoneCustomers { get; set; }
        public string FaxCustomers { get; set; }
        public string MasothueCustomers { get; set; }
        public Nullable<int> StatusCustomers { get; set; }
        public Nullable<System.DateTime> CreateDateCustomers { get; set; }
        public Nullable<System.DateTime> ModifyDateCustomers { get; set; }
        public string CreateUserCustomers { get; set; }
        public string ModifyUserCustomers { get; set; }
        public string NoteCustomer { get; set; }
        public string DiachiCustomers { get; set; }
    }
}
