//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhutLongCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductionCommand
    {
        public int Id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string Loai1 { get; set; }
        public string Loai2 { get; set; }
        public string Loai3 { get; set; }
        public string Loai4 { get; set; }
        public string Loai5 { get; set; }
        public string Loai6 { get; set; }
        public string Loai7 { get; set; }
        public Nullable<double> SoLuongSX { get; set; }
        public Nullable<double> DinhLuong1 { get; set; }
        public Nullable<double> DinhLuong2 { get; set; }
        public Nullable<double> DinhLuong3 { get; set; }
        public Nullable<double> DinhLuong4 { get; set; }
        public Nullable<double> DinhLuong5 { get; set; }
        public Nullable<double> DinhLuong6 { get; set; }
        public Nullable<double> DinhLuong7 { get; set; }
        public Nullable<double> KhoCuon1 { get; set; }
        public Nullable<double> KhoCuon2 { get; set; }
        public Nullable<double> KhoCuon3 { get; set; }
        public Nullable<double> KhoCuon4 { get; set; }
        public Nullable<double> KhoCuon5 { get; set; }
        public Nullable<double> KhoCuon6 { get; set; }
        public Nullable<double> KhoCuon7 { get; set; }
        public Nullable<double> Dai { get; set; }
        public Nullable<double> Rong { get; set; }
        public Nullable<int> BuHao { get; set; }
        public Nullable<double> KhoGiay { get; set; }
        public string NguoiLap { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    }
}
