//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhutLongCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrint
    {
        public int Id { get; set; }
        public Nullable<int> IdOrderTem { get; set; }
        public string CodeProducts { get; set; }
        public string NameProducts { get; set; }
        public string KhoDonDoi { get; set; }
        public string SoLop { get; set; }
        public string LoaiSong { get; set; }
        public string KhoGiaySX { get; set; }
        public string SoLuongSX { get; set; }
        public string LoaiGiay1 { get; set; }
        public string LoaiGiay2 { get; set; }
        public string LoaiGiay3 { get; set; }
        public string LoaiGiay4 { get; set; }
        public string LoaiGiay5 { get; set; }
        public string LoaiGiay6 { get; set; }
        public string DinhLuong { get; set; }
        public string DinhLuong1 { get; set; }
        public string DinhLuong2 { get; set; }
        public string DinhLuong3 { get; set; }
        public string DinhLuong4 { get; set; }
        public string DinhLuong5 { get; set; }
        public string DinhLuong6 { get; set; }
        public string KhoCuon1 { get; set; }
        public string KhoCuon2 { get; set; }
        public string KhoCuon3 { get; set; }
        public string KhoCuon4 { get; set; }
        public string KhoCuon5 { get; set; }
        public string KhoCuon6 { get; set; }
        public string DxRxC1 { get; set; }
        public string DxRxC2 { get; set; }
        public string DxRxC3 { get; set; }
        public string SoLuong { get; set; }
        public string InFlexo { get; set; }
        public string ThanhPham { get; set; }
    }
}
